<div class="container">
    <div id="block-login" class="col-lg-4 col-lg-offset-4  col-md-4 col-md-offset-4  col-sm-4 col-sm-offset-4  col-xs-12">

        <form role="form" action="<?php echo $this->basePath(false) ?>main/home/try-login" method="post" class="form-horizontal">
            <a href="<?php echo $this->basePath(false) ?>" class="brand brand-medium"></a>
            <div class="panel panel-warning">
                <div class="panel-heading">Informe o login</div>
                <div class="panel-body">
                    <div class="form-group">
                        <div class="col-lg-12 col-md-12">
                            <input type="text" class="form-control" id="usuario" name="usuario" placeholder="Usuário" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-12 col-md-12">
                            <input type="password" class="form-control" id="senha" name="senha" placeholder="Senha" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-12">
                            <button type="submit" class="col-lg-12 btn-lg btn btn-warning">Entrar</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>

    </div>
</div>