<!-- HTML CODE -->
  <div id="carrocelDocs" class="carrocelDocs">
        <label>Documentos de Identificação</label>            
        <div id="listaDocs" class="listaDocs">
            <div id="boxlista">            
                <div id="boxDocs" class="desativadoTrue desativado boxDocs">
                    <div id="checkDocs" class="checkedFalse" data-id="0"></div>
                    <div id="tituloDocs" class="tituloDocs" data-id="0" data-label="RG - Registro Geral" data-retorno="combo"><label>RG - Registro Geral</label></div>
                    <div id="quantidadeDocs"><input type="text" id="0" class="numerico" value="0" maxlength="2" data-id="0"/><input type="hidden" id="0" class="max" value="99"></div>
                    <div id="imagemDocs" class="DocRG imagemDocs" data-id="0"></div>
                    <div id="maisDocs"><a href="#" id="0" class="maisDocs"></a></div>
                    <div id="menosDocs"><a href="#" id="0" class="menosDocs"></a></div>
                </div>
                <div id="boxDocs" class="desativadoTrue desativado boxDocs">
                    <div id="checkDocs" class="checkedFalse" data-id="1"></div>
                    <div id="tituloDocs" class="tituloDocs"  data-id="1" data-label="CPF - PVC" data-retorno="qtde"><label>CPF - PVC</label></div>
                    <div id="quantidadeDocs"><input type="text" id="1" class="numerico" value="0" maxlength="2" data-id="1"/><input type="hidden" id="0" class="max" value="99"></div>
                    <div id="imagemDocs" class="DocCPF imagemDocs" data-id="1"></div>
                    <div id="maisDocs"><a href="#" id="1" class="maisDocs"></a></div>
                    <div id="menosDocs"><a href="#" id="1" class="menosDocs"></a></div>
                </div>
                <div id="boxDocs" class="desativadoTrue desativado boxDocs">
                    <div id="checkDocs" class="checkedFalse" data-id="2"></div>
                    <div id="tituloDocs" class="tituloDocs" data-id="2" data-label="CPF - Celulose" data-retorno="qtde"><label>CPF - Celulose</label></div>
                    <div id="quantidadeDocs"><input type="text" id="2" class="numerico" value="0" maxlength="2" data-id="2"/><input type="hidden" id="0" class="max" value="99"></div>
                    <div id="imagemDocs" class="DocCPF2 imagemDocs" data-id="2"></div>
                    <div id="maisDocs"><a href="#" id="2" class="maisDocs"></a></div>
                    <div id="menosDocs"><a href="#" id="2" class="menosDocs"></a></div>
                </div>
                <div id="boxDocs" class="desativadoTrue desativado boxDocs">
                    <div id="checkDocs" class="checkedFalse" data-id="3"></div>
                    <div id="tituloDocs" class="tituloDocs"  data-id="3" data-label="CNH - Atual" data-retorno="combo"><label>CNH - Atual</label></div>
                    <div id="quantidadeDocs"><input type="text" id="3" class="numerico" value="0" maxlength="2" data-id="3"/><input type="hidden" id="0" class="max" value="99"></div>
                    <div id="imagemDocs" class="DocCNH imagemDocs" data-id="3"></div>
                    <div id="maisDocs"><a href="#" id="3" class="maisDocs"></a></div>
                    <div id="menosDocs"><a href="#" id="3" class="menosDocs"></a></div>
                </div>
                <div id="boxDocs" class="desativadoTrue desativado boxDocs">
                    <div id="checkDocs" class="checkedFalse" data-id="4"></div>
                    <div id="tituloDocs" class="tituloDocs"  data-id="4" data-label="CNH - Antiga" data-retorno="combo"><label>CNH - Antiga</label></div>
                    <div id="quantidadeDocs"><input type="text" id="4" class="numerico" value="0" maxlength="2" data-id="4"/><input type="hidden" id="0" class="max" value="99"></div>
                    <div id="imagemDocs" class="DocCNH2 imagemDocs" data-id="4"></div>
                    <div id="maisDocs"><a href="#" id="4" class="maisDocs"></a></div>
                    <div id="menosDocs"><a href="#" id="4" class="menosDocs"></a></div>
                </div>
                <div id="boxDocs" class="desativadoTrue desativado boxDocs">
                    <div id="checkDocs" class="checkedFalse" data-id="5"></div>
                    <div id="tituloDocs" class="tituloDocs"  data-id="5" data-label="Carteira OAB" data-retorno="qtde"><label>Carteira OAB</label></div>
                    <div id="quantidadeDocs"><input type="text" id="5" class="numerico" value="0" maxlength="2" data-id="5"/><input type="hidden" id="0" class="max" value="99"></div>
                    <div id="imagemDocs" class="DocOAB imagemDocs" data-id="5"></div>
                    <div id="maisDocs"><a href="#" id="5" class="maisDocs"></a></div>
                    <div id="menosDocs"><a href="#" id="5" class="menosDocs"></a></div>
                </div>                            
            </div>                                               
        </div>
    </div>