<div class="row-fluid">
    <a href="/gerador/entidades" class="span6 btn center btn-entidades">
        <span class="title">Entidades</span>
    </a>
    <a href="/gerador/modulos" class="span6 btn center btn-modulos">
        <span class="title">Módulos</span>
    </a>
</div>
<br />
<div class="row-fluid">
    <div class="span6 desc-entidades img-polaroid img-rounded">
        <legend>Entidades do Sistema</legend>
        <dl class="unstyled">
            <?php foreach ($this->models as $_module => $models): ?>
                <dt><a href="/<?php echo strtolower($_module) ?>"><?php echo $_module ? $_module : 'Home' ?></a></dt>
                <?php foreach ($models as $_model): ?>
                    <dd><?php echo $_model ?></dd>
                <?php endforeach; ?>
            <?php endforeach; ?>
        </dl>
    </div>
    <div class="span6 desc-modules img-polaroid img-rounded">
        <legend>Módulos do Sistema</legend>
        <ul class="unstyled">
            <?php foreach ($this->modules as $_module): ?>
                <li><a href="/<?php echo strtolower($_module) ?>"><?php echo $_module ? $_module : 'Home' ?></a></li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>