<?php
$form = $this->form;
$form->setAttribute('action', $this->url('gerencial', array('controller' => 'perfis', 'action' => 'edit', 'id' => $this->id))); //@s @todo int_cod
$form->prepare();
?>

<div class="tabbable">
    <?php echo $this->menu_principal; ?>
    <div class="tab-content">
        <p>
        <h1><?php echo $this->escapeHtml('Editar Perfil'); ?></h1>

        <?php
        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('int_cod'));
        echo $this->formRow($form->get('str_nome'));
        echo $this->formRow($form->get('int_situacao'));
        ?>
        <div class="control-group">
            <div class="controls">
                <?php echo $this->formSubmit($form->get('submit')); ?>
            </div>
        </div>
        <?php echo $this->form()->closeTag(); ?>
        </p>
    </div>
</div>

