
<?php foreach ($this->map as $_schema => $_tables): ?>
    <?php if (count($_tables)): ?>
        <table class="table table-condensed  table-bordered table-striped table-hover">
            <thead>
                <tr>
                    <th>Schema.Table</th>
                    <th width="5%" class="center">Cols.</th>
                    <th width="5%" class="center">Attr.</th>
                    <th width="18%">Controller</th>
                    <th width="18%">Form</th>
                    <th width="18%">Service</th>
                    <th width="18%">Model</th>
                    <th width="5%"></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_tables as $_table => $_columns): ?>
                    <tr>
                        <td><?php echo "{$_schema}.{$_table}"; ?></td>
                        <td class="center"><?php echo count($_columns); ?></td>
                        <td class="center"><?php echo isset($this->classes[$_schema][$_table]['service']) ? count($this->classes[$_schema][$_table]['service'][1]) : '-' ?></td>
                        <td><small class="muted"><?php echo isset($this->classes[$_schema][$_table]['controller']) ? $this->classes[$_schema][$_table]['controller'][0] : '-' ?></small></td>
                        <td><small class="muted"><?php echo isset($this->classes[$_schema][$_table]['form']) ? $this->classes[$_schema][$_table]['form'][0] : '-' ?></small></td>
                        <td><small class="muted"><?php echo isset($this->classes[$_schema][$_table]['service']) ? $this->classes[$_schema][$_table]['service'][0] : '-' ?></small></td>
                        <td><small class="muted"><?php echo isset($this->classes[$_schema][$_table]['model']) ? $this->classes[$_schema][$_table]['model'][0] : '-' ?></small></td>
                        <td class="center">
                            <a class="btn btn-info bt-nova-entidade" title="Novo" href="#" data-schema="<?php echo $_schema ?>" data-table="<?php echo $_table ?>">
                                <i class="icon-plus icon-white"></i>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
        </table>
    <?php endif; ?>
<?php endforeach; ?>