<?php
$form = $this->form;
$form->setAttribute('action', $this->url('artigos', array('controller' => 'artigo', 'action' => 'edit', 'id' => $this->id)));
$form->prepare();
?>

<h2><?php echo $this->escapeHtml('Editar Artigo'); ?></h2>
<hr />

<?php
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('int_cod'));
echo $this->formHidden($form->get('int_redator'));
echo $this->formHidden($form->get('dat_criacao'));
echo $this->formRow($form->get('dat_inicio_publicacao'));
echo $this->formRow($form->get('dat_fim_publicacao'));
echo $this->formRow($form->get('str_chamada'));
echo $this->formRow($form->get('str_titulo'));
echo $this->formRow($form->get('str_conteudo'));
echo $this->formRow($form->get('int_destaque'));
echo $this->formRow($form->get('str_img_destaque'));
?>
<div class="control-group">
    <div class="controls">
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>

<div id="galeriaFotos" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-remote="/galeria-fotos">
    <input type="hidden" id="galeria-fotos-imagem-selecionada" />
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Galeria de Imagens</h3>
    </div>
    <div class="modal-body">

    </div>
    <div class="modal-footer">
        <button class="btn" aria-hidden="true" id="btn-galeria-fotos-cancelar">Cancelar</button>
        <button class="btn btn-primary" id="btn-galeria-fotos-selecionar-imagem">Selecionar</button>
    </div>
</div>
