<form method="post" class="form-horizontal">
    <div class="control-group">
        <label class="control-label" for="nmModulo">Módulo</label>
        <div class="controls">
            <input type="text" id="nmModulo" name="nmModulo" placeholder="Nome do Módulo">
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <button type="submit" class="btn btn-primary">Criar Módulo</button>
        </div>
    </div>
</form>