<?php
$title = 'Novo Perfil';
$this->headTitle($title);
?>
<div class="panel panel-default">
    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url(null, array('module' => 'main', 'controller' => 'perfil', 'action' => 'edit', 'id' => $id)));
    $form->prepare();

    echo <<<HTML
    <div class='panel-heading'>
        {$this->escapeHtml($title)}
        <p class='pull-right'>
            <a href='{$this->url(null, array('module' => 'main', 'controller' => 'perfil'))}'>Lista de Perfis</a>
        </p>
    </div>
HTML;

    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('intCod'));
    ?>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('strNome')); ?>
        <?php echo $this->formElementErrors($form->get('strNome')); ?>
        <div class="col-lg-6">
            <?php echo $this->formElement($form->get('strNome')); ?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('intSituacao')); ?>
        <?php echo $this->formElementErrors($form->get('intSituacao')); ?>
        <div class="col-lg-2">
            <?php echo $this->formCheckbox($form->get('intSituacao')); ?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10">
            <?php echo $this->formSubmit($form->get('submit')); ?>
        </div>
    </div>
    <?php echo $this->form()->closeTag(); ?>
</div>