<div class="panel panel-default">
    <div class="panel-heading">
        Perfis
        <p class="pull-right">
            <a href="<?php echo $this->url(null, array('module' => 'main', 'controller' => 'perfil', 'action' => 'add')); ?>">Novo Perfil</a>
        </p>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th width="5%" class="text-center">ID</th>
                <th width="60%">Nome</th>
                <th class="text-center" width="10%">Acessos</th>
                <th class="text-center" width="10%">Situação</th>
                <th class="text-center" width="5%">Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php if (count($datagrid)) : ?>
                <?php foreach ($datagrid as $perfil): ?>
                    <tr>
                        <td class="text-center"><?php echo $perfil->getIntCod() ?></td>
                        <td><?php echo $perfil->getStrNome() ?><span class="badge pull-right"><?php echo count($perfil->getColAcessos()) ?></span></td>
                        <td class="text-center">
                            <a href="<?php echo $this->url(null, array('module' => 'main', 'controller' => 'perfil', 'action' => 'resources', 'id' => $perfil->getIntCod())) ?>"><span class="icon-link glyphicon glyphicon-new-window"></span></a>
                        </td>
                        <td class="text-center">
                            <span class="glyphicon glyphicon-<?php echo $perfil->getIntSituacao() == 0 ? 'minus-sign' : 'ok-sign icon-success' ?>"></span>
                        </td>
                        <td class="text-center">
                            <a href="<?php echo $this->url(null, array('module' => 'main', 'controller' => 'perfil', 'action' => 'edit', 'id' => $perfil->getIntCod())) ?>"><span class="glyphicon glyphicon-edit"></span></a>
                            <a href="<?php echo $this->url(null, array('module' => 'main', 'controller' => 'perfil', 'action' => 'remove', 'id' => $perfil->getIntCod())) ?>"><span class="glyphicon glyphicon-remove"></span></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="5">Nenhum resultado encontrado.</td>
                </tr>
            <?php endif; ?>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="5" class="text-center">
                    <?php echo $this->paginationControl($datagrid, 'sliding', array('components/paginator.phtml', 'Perfis'), array('route' => array('module' => 'main', 'controller' => 'perfil'))) ?>
                </td>
            </tr>
        </tfoot>
    </table>
</div>