<form class="form-horizontal" role="form" action="#" method="post">
    <div class="panel panel-default">
        <div class='panel-heading'>
            <?php echo $perfil->getStrNome() ?>
            <a id="bt-select-all" class="pull-right" href="#">Selecionar todos</a>
        </div>
        <table id="tb-resources" class="table table-bordered table-condensed table-hover table-responsive table-striped">
            <thead>
                <tr>
                    <th>Módulo</th>
                    <th>Controller</th>
                    <th>Action</th>
                    <th>Info</th>
                    <th width="5%">Acões</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($resources as $resource): ?>
                    <?php $route = explode('|', $resource) ?>
                    <?php $boComment = key_exists($resource, $comments) ?>
                    <tr>
                        <td><?php echo $route[0] ?></td>
                        <td><?php echo $route[1] ?></td>
                        <td><?php echo $route[2] ?></td>
                        <td><em class="text-muted"><?php echo $boComment ? $comments[$resource] : '' ?></em></td>
                        <td>
                            <label>
                                <input name="<?php echo $resource ?>" type="checkbox" <?php echo in_array($resource, $acessos) ? 'checked="checked"' : '' ?> />
                            </label>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="5" class="text-right">
                        <button type="submit" class="btn btn-primary">Salvar</button>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
</form>