<div class="tabbable">
    <?php echo $this->menu_principal; ?>
    <div class="tab-content">
        <p>
            <dl class="dl-horizontal">
                <dt><a href="<?php echo $this->url('gerencial', array('controller' => 'usuarios')) ?>" title="Ir para tela de Usuários">Usuários</a></dt>
                <dd><?php echo $this->totais['usuarios'] ?></dd>
                <dt><a href="<?php echo $this->url('gerencial', array('controller' => 'perfis')) ?>" title="Ir para tela de Perfis">Perfis</a></dt>
                <dd><?php echo $this->totais['perfis'] ?></dd>
                <dt><a href="<?php echo $this->url('gerencial', array('controller' => 'menus')) ?>" title="Ir para tela de Menus">Menus</a></dt>
                <dd><?php echo $this->totais['menus'] ?></dd>
                <dt><a href="<?php echo $this->url('gerencial', array('controller' => 'menus')) ?>" title="Ir para tela de Itens de Menus">Itens de Menu</a></dt>
                <dd><?php echo $this->totais['menus_items'] ?></dd>
                <dt><a href="<?php echo $this->url('gerencial', array('controller' => 'acessos')) ?>" title="Ir para tela de Acessos">Acessos</a></dt>
                <dd><?php echo $this->totais['acessos'] ?></dd>
            </dl>
        </p>
    </div>
</div>