<?php

return array(
    'FS\Entity\Entity' => 'vendor/FS/Entity/Entity.php',
    'FS\Controller\Controller' => 'vendor/FS/Controller/Controller.php',
    'FS\Controller\ControllerLivre' => 'vendor/FS/Controller/ControllerLivre.php',
    'FS\Model\Model' => 'vendor/FS/Model/Model.php',
    'FS\Model\Service' => 'vendor/FS/Model/Service.php',
    'FS\Image\Resize' => 'vendor/FS/Image/Resize.php',
    'FS\Permissions\Acl' => 'vendor/FS/Permissions/Acl.php',
    'FS\Auth\AuthStorage' => 'vendor/FS/Auth/AuthStorage.php',
    'FS\Session\Storage' => 'vendor/FS/Session/Storage.php',
    'FS\Types\ArrayUtil' => 'vendor/FS/Types/ArrayUtil.php',
    'FS\Feed\Rss' => 'vendor/FS/Feed/Rss.php',
    'FS\View\Form' => 'vendor/FS/View/Form.php',
    'FS\View\Tree' => 'vendor/FS/View/Tree.php',
    'FS\View\DataGrid' => 'vendor/FS/View/DataGrid.php',
    'FS\View\DatagridFilter' => 'vendor/FS/View/DatagridFilter.php',
    'FS\View\SearchFilter' => 'vendor/FS/View/SearchFilter.php',
    'FS\View\Helper\FormRow' => 'vendor/FS/View/Helper/FormRow.php',
    'FS\View\Helper\FormSubmit' => 'vendor/FS/View/Helper/FormSubmit.php',
    'FS\View\Helper\FormLabel' => 'vendor/FS/View/Helper/FormLabel.php',
    'FS\View\Helper\DateFormat' => 'vendor/FS/View/Helper/DateFormat.php',
    'FS\View\Helper\BasePath' => 'vendor/FS/View/Helper/BasePath.php',
);