<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
        <?php echo $this->headTitle('Rubix')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <?php
        $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . 'img/favicon.ico'))
                ->prependStylesheet($this->basePath() . 'css/global.css')
                ->prependStylesheet($this->basePath() . 'css/bootstrap/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . 'css/bootstrap/bootstrap.min.css');

        if ($this->lstCss && is_array($this->lstCss)) {
            foreach ($this->lstCss as $_cssFile) {
                $this->headLink()->appendStylesheet("{$this->basePath()}css/{$_cssFile}");
            }
        }

        echo $this->headLink();
        ?>
    </head>
    <body>
        <?php
        echo "<script>\n";
        echo "\t\tvar msgSuccess = [];\n";
        echo "\t\tvar msgError = [];\n";
        echo "\t\t</script>\n";
        ?>
        <br />
        <div class="container">
            <div class="col-lg-6 col-lg-offset-3">
                <form class="form-horizontal">
                    <a style="margin: 10px auto;" href="<?php echo $this->basePath(false) ?>" class="brand"></a>
                    <div class="panel panel-danger">
                        <div class="panel-heading" style="padding-bottom: 0;">
                            <h1 style="font-size: 2em;"><?php echo $this->translate('A 404 error occurred') ?></h1>
                            <h2><?php echo $this->message ?></h2>
                        </div>
                        <div class="panel-body">
                            <?php if (isset($this->reason) && $this->reason): ?>

                                <?php
                                $reasonMessage = '';
                                switch ($this->reason) {
                                    case 'error-controller-cannot-dispatch':
                                        $reasonMessage = $this->translate('The requested controller was unable to dispatch the request.');
                                        break;
                                    case 'error-controller-not-found':
                                        $reasonMessage = $this->translate('The requested controller could not be mapped to an existing controller class.');
                                        break;
                                    case 'error-controller-invalid':
                                        $reasonMessage = $this->translate('The requested controller was not dispatchable.');
                                        break;
                                    case 'error-router-no-match':
                                        $reasonMessage = $this->translate('The requested URL could not be matched by routing.');
                                        break;
                                    default:
                                        $reasonMessage = $this->translate('We cannot determine at this time why a 404 was generated.');
                                        break;
                                }
                                ?>

                                <p><?php echo $reasonMessage ?></p>

                            <?php endif ?>

                            <dl>
                                <?php if (isset($this->module) && $this->module): ?>
                                    <dt><?php echo $this->translate('Module') ?>:</dt>
                                    <dd><?php echo $this->escapeHtml($this->module) ?></dd>
                                <?php endif ?>
                                <?php if (isset($this->controller) && $this->controller): ?>
                                    <dt><?php echo $this->translate('Controller') ?>:</dt>
                                    <dd><?php echo $this->escapeHtml($this->controller) ?>
                                        <?php
                                        if (isset($this->controller_class)
                                                && $this->controller_class
                                                && $this->controller_class != $this->controller
                                        ) {
                                            echo '(' . sprintf($this->translate('resolves to %s'), $this->escapeHtml($this->controller_class)) . ')';
                                        }
                                        ?>
                                    </dd>
                                <?php endif ?>
                                <?php if (isset($this->action) && $this->action): ?>
                                    <dt><?php echo $this->translate('Action') ?>:</dt>
                                    <dd><?php echo $this->escapeHtml($this->action) ?></dd>
                                <?php endif ?>
                            </dl>

                            <?php if (isset($this->display_exceptions) && $this->display_exceptions): ?>

                                <?php if (isset($this->exception) && $this->exception instanceof Exception): ?>
                                    <hr/>
                                    <h2><?php echo $this->translate('Additional information') ?>:</h2>
                                    <h3><?php echo get_class($this->exception); ?></h3>
                                    <dl>
                                        <dt><?php echo $this->translate('File') ?>:</dt>
                                        <dd>
                                            <pre class="prettyprint linenums"><?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine() ?></pre>
                                        </dd>
                                        <dt><?php echo $this->translate('Message') ?>:</dt>
                                        <dd>
                                            <pre class="prettyprint linenums"><?php echo $this->exception->getMessage() ?></pre>
                                        </dd>
                                        <dt><?php echo $this->translate('Stack trace') ?>:</dt>
                                        <dd>
                                            <pre class="prettyprint linenums"><?php echo $this->exception->getTraceAsString() ?></pre>
                                        </dd>
                                    </dl>
                                    <?php
                                    $e = $this->exception->getPrevious();
                                    if ($e) :
                                        ?>
                                        <hr/>
                                        <h2><?php echo $this->translate('Previous exceptions') ?>:</h2>
                                        <ul class="unstyled">
                                            <?php while ($e) : ?>
                                                <li>
                                                    <h3><?php echo get_class($e); ?></h3>
                                                    <dl>
                                                        <dt><?php echo $this->translate('File') ?>:</dt>
                                                        <dd>
                                                            <pre class="prettyprint linenums"><?php echo $e->getFile() ?>:<?php echo $e->getLine() ?></pre>
                                                        </dd>
                                                        <dt><?php echo $this->translate('Message') ?>:</dt>
                                                        <dd>
                                                            <pre class="prettyprint linenums"><?php echo $e->getMessage() ?></pre>
                                                        </dd>
                                                        <dt><?php echo $this->translate('Stack trace') ?>:</dt>
                                                        <dd>
                                                            <pre class="prettyprint linenums"><?php echo $e->getTraceAsString() ?></pre>
                                                        </dd>
                                                    </dl>
                                                </li>
                                                <?php
                                                $e = $e->getPrevious();
                                            endwhile;
                                            ?>
                                        </ul>
                                    <?php endif; ?>

                                <?php else: ?>

                                    <h3><?php echo $this->translate('No Exception available') ?></h3>

                                <?php endif ?>

                            <?php endif ?>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <?php
        //xd($this->module, $this->controller, $this->action, $this->controller_class, $this->message);
        ?>

        <?php
        $this->headScript()
                ->prependFile($this->basePath() . 'js/bootstrap/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9'))
                ->prependFile($this->basePath() . 'js/bootstrap/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9'))
                ->prependFile($this->basePath() . 'js/noty/themes/rubix.js')
                ->prependFile($this->basePath() . 'js/noty/themes/default.js')
                ->prependFile($this->basePath() . 'js/noty/layouts/top.js')
                ->prependFile($this->basePath() . 'js/noty/jquery.noty.js')
                ->prependFile($this->basePath() . 'js/bootstrap/bootstrap.min.js')
                ->prependFile($this->basePath() . 'js/jquery/jquery-ui.min.js')
                ->prependFile($this->basePath() . 'js/jquery/jquery-1.10.2.js');

        if ($this->lstExtraJavascripts && is_array($this->lstExtraJavascripts)) {
            foreach ($this->lstExtraJavascripts as $_jsFile) {
                $this->headScript()->appendFile("{$this->basePath()}/js/{$_jsFile}");
            }
        }

        $this->headScript()->appendFile($this->basePath() . 'js/global.js');

        if ($this->lstJavascripts && is_array($this->lstJavascripts)) {
            foreach ($this->lstJavascripts as $_jsFile) {
                $this->headScript()->appendFile("{$this->basePath()}js/modules/{$_jsFile}");
            }
        }

        echo $this->headScript();
        echo $this->inlineScript();
        ?>
    </body>
</html>