<?php
$form = $this->form;
$form->prepare();
?>
<div class="row-fluid">
    <div id="galeria-fotos-categorias" class="span3">
        <button id="btn-galeria-fotos-add-categoria" class="btn btn-mini pull-right" title="Nova categoria"><i class="icon-plus-sign"></i></button>
        <div id="categorias-listagem">
            <?php echo $this->categorias ?>
        </div>
    </div>
    <div id="galeria-fotos-listagem" class="span9 part-galeria">
        <button id="btn-galeria-fotos-add-imagem" class="btn btn-mini pull-right" title="Nova imagem"><i class="icon-plus-sign"></i></button>
        <div>
            <span class="span7" id="galeria-fotos-imagem"></span>
            <span class="span4" id="galeria-fotos-info">
                <dl>
                    <dt>Nome</dt>
                    <dd id="galeria-fotos-info-nome"></dd>
                    <dt>Tamanho</dt>
                    <dd id="galeria-fotos-info-tamanho"></dd>
                    <dt>Resolução</dt>
                    <dd id="galeria-fotos-info-resolucao"></dd>
                </dl>
            </span>
        </div>
    </div>
    <div id="galeria-fotos-cadastro" class="span9 hide part-cadastro">
        <button id="btn-galeria-fotos-voltar-listagem" class="btn btn-mini pull-right" title="Voltar"><i class="iconic-undo"></i></button>
        <div class="content">
            <?php
            echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('int_cod'));
            ?>
            <input type="hidden" id="galeria-fotos-ref-callback" />
            <input type="hidden" id="galeria-fotos-id" />
            <h4>Nova imagem</h4>
            <hr />
            <div class="span4">
                <div class="fileupload fileupload-new" data-provides="fileupload">
                    <div class="fileupload-new thumbnail" style="width: 200px; height: 150px;"><img src="/img/galeria-imagens-default.gif" /></div>
                    <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"></div>
                    <div>
                        <span class="btn btn-file"><span class="fileupload-new">Selecione a imagem</span><span class="fileupload-exists">Alterar</span><input id="galeria-fotos-img" name="galeria-fotos-img" type="file" required /></span>
                        <a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Cancelar</a>
                    </div>
                </div>
            </div>
            <div class="span7">
                <?php echo $this->formRow($form->get('str_nome')); ?>
                <div class="control-group">
                    <div class="controls">
                        <?php echo $this->formSubmit($form->get('submit')); ?>
                    </div>
                </div>
            </div>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
</div>

<div class="row-fluid part-galeria">
    <div id="galeria-fotos-thumbs" class="span12">

    </div>
</div>