<?php echo $this->doctype(); ?>

<html lang="pt">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('nome-aplicacao'))->setSeparator(' :: ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <?php
        $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/fs/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/markitup/sets/markdown/style.css')
                ->prependStylesheet($this->basePath() . '/css/markitup/macosx/style.css')
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ->prependStylesheet($this->basePath() . '/css/fs/jquery-ui-min.css')
                ->prependStylesheet($this->basePath() . '/css/jquery-ui-timepicker-addon.css');

        if ($this->lstCss && is_array($this->lstCss)) {
            foreach ($this->lstCss as $_cssFile) {
                $this->headLink()->appendStylesheet("{$this->basePath()}/css/modules/{$_cssFile}");
            }
        }

        echo $this->headLink();
        ?>
    </head>
    <body>
        <?php if ($this->booMostrarBarraTopo || !isset($this->booMostrarBarraTopo)) : ?>
            <div id="fs-navbar-top" class="navbar navbar-fixed-top <?php echo $this->strClasseBarraTopo ?>">
                <div class="navbar-inner">
                    <div class="container">
                        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </a>
                        <a class="brand brand-left" href="<?php //echo $this->url('home') ?>"><?php echo $this->translate('nome-aplicacao') ?></a>
                        <div class="nav-collapse collapse">
                            <?php echo $this->booMostrarMenuPrincipal || ($this->menu_principal && !isset($this->booMostrarMenuPrincipal)) ? $this->menu_principal : ''; ?>
                            <?php echo $this->booMostrarMenuDireita || ($this->menu_direita && !isset($this->booMostrarMenuDireita)) ? $this->menu_direita : ''; ?>
                        </div><!--/.nav-collapse -->
                    </div>
                </div>
            </div>
        <?php endif; ?>
        <div class="container">
            <input type="hidden" name="url-old" id="url-old" value="" />
            <?php
            if ($this->mensagensSucesso) {
                foreach ($this->mensagensSucesso as $mensagem) :
                    ?>
                    <div class="alert alert-success fade in">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <h4><?php echo $this->translate('Sucesso!'); ?></h4>
                        <?php echo $this->translate($mensagem); ?>
                    </div>
                    <?php
                endforeach;
            }
            if ($this->mensagensErro) {
                foreach ($this->mensagensErro as $mensagem) :
                    ?>
                    <div class="alert alert-error fade in">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <h4><?php echo $this->translate('Falha!'); ?></h4>
                        <?php echo $this->translate($mensagem); ?>
                    </div>
                    <?php
                endforeach;
            }
            ?>
            <?php if (count($this->breadcrumbs) > 0) : ?>
                <ul class="breadcrumb">
                    <?php
                    $breadcrumbs = $this->breadcrumbs;
                    $keysBreadcrumb = array_keys($breadcrumbs);

                    $lastLabelBreadcrumb = $keysBreadcrumb[count($breadcrumbs) - 1];
                    array_pop($breadcrumbs);
                    ?>
                    <?php foreach ($breadcrumbs as $label => $url): ?>
                        <li><a href="<?php echo $url; ?>"><?php echo $label; ?></a> <span class="divider">/</span></li>
                    <?php endforeach; ?>
                    <li class="active"><?php echo $lastLabelBreadcrumb; ?></li>
                </ul>
            <?php endif; ?>

            <?php echo $this->content; ?>
        </div> <!-- /container -->

        <?php if ($this->booMostrarRodape || !isset($this->booMostrarRodape)) : ?>
            <div id="footer">
                <div class="container">
                    <div class="row-fluid">
                        <div class="span4">
                            <h5><i class="icon-map-marker icon-white"></i>&nbsp;&nbsp;Mapa do Site</h5>
                            <small>
                                <ul class="unstyled">
                                    <li><i class="icon-chevron-right icon-white"></i>&nbsp;<a href="./">Principal</a></li>
                                    <li><i class="icon-chevron-right icon-white"></i>&nbsp;<a href="#">Produtos</a>
                                        <ul class="unstyled text-indent-2em">
                                            <li><i class="icon-chevron-right icon-white"></i>&nbsp;<a href="./apps-ios">Apps para iPhone/iPad</a></li>
                                            <li><i class="icon-chevron-right icon-white"></i>&nbsp;<a href="#">Sistemas de Gestão</a></li>
                                            <li><i class="icon-chevron-right icon-white"></i>&nbsp;<a href="#">Sites Empresariais</a></li>
                                            <li><i class="icon-chevron-right icon-white"></i>&nbsp;<a href="#">Advergames</a></li>
                                        </ul>
                                    </li>
                                    <li><i class="icon-chevron-right icon-white"></i>&nbsp;<a href="#">Clientes</a></li>
                                    <li><i class="icon-chevron-right icon-white"></i>&nbsp;<a href="#">Suporte</a></li>
                                    <li><i class="icon-chevron-right icon-white"></i>&nbsp;<a href="#">Contato</a></li>
                                </ul>
                            </small>
                        </div>
                        <div class="span4">
                            <h5><i class="icon-info-sign icon-white"></i>&nbsp;&nbsp;Contato</h5>
                            <small>
                                <ul class="unstyled">
                                    <li>
                                        <span class="label label-important">E-mail</span>&nbsp; contato@fontesolutions.com.br
                                    </li>
                                    <li>
                                        <span class="label label-important">Celular</span>&nbsp; 55 (61) 9621-2011<br>
                                    </li>
                                    <li>
                                        <span class="label label-important">Comercial</span>&nbsp; 55 (61) 3046-5726<br>
                                    </li>
                                </ul>
                            </small>
                        </div>
                        <div class="span4">
                            <h5><i class="icon-briefcase icon-white"></i>&nbsp;&nbsp;Parceiros</h5>
                            <small>
                                <ul class="unstyled">
                                    <li><i class="icon-thumbs-up icon-white"></i>&nbsp;<a href="http://digitalbrasilia.com.br/" target="_blank">DigitalBrasilia</a></li>
                                </ul>
                            </small>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container-fluid" id="sub-footer">
                <div class="span12">
                    <p><small>&copy; 2011 - <?php echo date('Y') ?> FonteSolutions. <?php echo $this->translate('Todos os direitos reservados.') ?></small></p>
                </div>
            </div>
        <?php endif; ?>


        <?php
        $this->headScript()
                //->prependFile($this->basePath() . '/js/log.js')
                ->prependFile($this->basePath() . '/js/markitup/sets/markdown/set.js')
                ->prependFile($this->basePath() . '/js/jquery.markitup.js')
                ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery-ui-timepicker-addon.js')
                ->prependFile($this->basePath() . '/js/jquery-ui-sliderAccess.js')
                ->prependFile($this->basePath() . '/js/jquery-ui.min.js')
                ->prependFile($this->basePath() . '/js/i18n/jquery-ui-i18n.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js');

        if ($this->lstExtraJavascripts && is_array($this->lstExtraJavascripts)) {
            foreach ($this->lstExtraJavascripts as $_jsFile) {
                $this->headScript()->appendFile("{$this->basePath()}/js/{$_jsFile}");
            }
        }

        $this->headScript()->appendFile($this->basePath() . '/js/global.js');

        if ($this->lstJavascripts && is_array($this->lstJavascripts)) {
            foreach ($this->lstJavascripts as $_jsFile) {
                $this->headScript()->appendFile("{$this->basePath()}/js/modules/{$_jsFile}");
            }
        }

        echo $this->headScript();
        echo $this->inlineScript();
        ?>
    </body>
</html>
