<input type="hidden" name="int_cod" value="<?php echo $this->menu->cod ?>" />
<input type="hidden" name="int_menu" value="<?php echo $this->menu->codMenu ?>" />
<dl class="dl-horizontal">
    <dt>Pai:</dt>
    <dd><?php echo $this->menu->labelPai ?>&nbsp;</dd>
    <dt>Label:</dt>
    <dd><?php echo $this->menu->label ?>&nbsp;</dd>
    <dt>Url:</dt>
    <dd><?php echo $this->menu->target ?>&nbsp;</dd>
    <dt>Posição:</dt>
    <dd><?php echo $this->menu->posicao ?>&nbsp;</dd>
    <!--dt>Menu:</dt>
    <dd><?php //echo $this->menu->codMenu ?>&nbsp;</dd-->
    <dt>Tipo:</dt>
    <dd><?php echo $this->menu->tipo ?>&nbsp;</dd>
</dl>
