<?php
$form = $this->form;
$form->prepare();
$formMenus = $this->formMenus;
$formMenus->prepare();
?>

<div class="tabbable">
    <?php echo $this->menu_principal; ?>
    <div class="tab-content">
        <p>
        <div class="row-fluid">
            <div id="menu-select" class="span3 well">
                <?php
                echo $this->form()->openTag($formMenus);
                echo $this->formRow($form->get('int_menu'));
                echo $this->form()->closeTag();
                ?>
            </div>

            <div id="menus-tree" class="span4 well">
                <ul>
                    <?php foreach ($this->menusItems as $_menu): ?>
                        <li id="menu<?php echo $_menu['int_cod'] ?>" data-id="<?php echo $_menu['int_cod'] ?>">
                            <a href="<?php echo $_menu['str_target'] ?>"><?php echo $_menu['str_label'] ?></a>

                            <?php if (isset($_menu['items']) && is_array($_menu['items'])): ?>
                                <ul>
                                    <?php foreach ($_menu['items'] as $_filho): ?>
                                        <li id="menu<?php echo $_filho['int_cod'] ?>" data-id="<?php echo $_filho['int_cod'] ?>">
                                            <a href="<?php echo $_filho['str_target'] ?>"><?php echo $_filho['str_label'] ?></a>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            <?php endif; ?>

                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <div class="span4">
                <div class="">
                    <p>
                        <a id="btn-add-item" href="#" class="btn" title="Adicionar um novo item"><i class="icon-plus"></i> Adicionar Item</a>
                        <a id="btn-remove-item" href="#" class="btn" title="Remover um item"><i class="icon-trash"></i> Excluir</a>
                        <a id="btn-gerar-menu" href="#" class="btn" title="Salvar o menu em arquivo físico"><i class="icon-file"></i> Gerar Menu</a>
                    </p>

                    <?php
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($form->get('int_cod'));
                    echo $this->formRow($form->get('int_cod_pai'));
                    echo $this->formRow($form->get('str_label'));
                    echo $this->formRow($form->get('str_target'));
                    echo $this->formRow($form->get('int_posicao'));
                    echo $this->formRow($form->get('str_tipo'));
                    ?>
                    <input type="hidden" name="int_menu" id="int_menu_clone" value="" />
                    <div class="control-group">
                        <div class="controls">
                            <?php echo $this->formSubmit($form->get('submit')); ?>
                        </div>
                    </div>
                    <?php echo $this->form()->closeTag(); ?>

                </div>
            </div>
        </div>
        </p>
    </div>
</div>

<div id="mod-excluir" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <form action="" data-action-original="/gerencial/menus/delete/" method="post">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="myModalLabel">Excluir menu</h3>
        </div>
        <div class="modal-body">
            <p>Tem certeza que deseja excluir o menu?</p>
            <div id="mod-excluir-body"></div>
        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
            <input type="submit" class="btn btn-danger" value="Excluir" />
        </div>
    </form>
</div>