<div class="panel panel-default panel-datagrid">

    <div class="panel-heading">
        <?php echo $title ?>
        <?php if(count($header)): ?>
            <p class="pull-right">
                <?php foreach($header as $link): ?>
                    <?php
                    $type = '';
                    switch($link['type']) :
                        case \Rubix\View\Components\Datagrid::HEADER_BUTTON:
                            $type = 'warning';
                            break;
                        case \Rubix\View\Components\Datagrid::HEADER_LINK:
                            $type = 'link';
                            break;
                    endswitch;
                    ?>
                    <a class="btn btn-xs btn-<?php echo $type ?>" href="<?php echo $this->url(null, $link['link']); ?>">
                        <?php if($link['icon']): ?>
                            <span class="glyphicon glyphicon-<?php echo $link['icon'] ?>"></span>
                        <?php endif; ?>
                        <?php echo $link['label'] ?>
                    </a>
                <?php endforeach; ?>
            </p>
        <?php endif; ?>
    </div>

    <table class="table table-bordered table-condensed table-hover table-responsive table-striped datagrid">
        <thead>
            <tr>

                <?php foreach ($columns as $name => $col): ?>
                    <?php $attrs = ''; ?>
                    <?php if(isset($col['options']) && isset($col['options']['attributes'])): ?>
                        <?php foreach($col['options']['attributes'] as $attr => $val): ?>
                            <?php $attrs.= "{$attr}=\"{$val}\" "; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>

                    <th <?php echo $attrs ?>>
                        <?php echo $col['label'] ?>
                        <?php if($col['aliasOrderBy']): ?>
                            <a href="<?php echo $this->url(null, $url['paginator']); ?>?sortfield=<?php echo $name; ?>&sortorder=<?php echo $sortOrder; ?>">
                                <span class="<?php echo $name == $sortField ? 'rubix-color' : '' ?> datagrid-sorter glyphicon glyphicon-sort"></span>
                            </a>
                        <?php endif; ?>
                    </th>

                <?php endforeach; ?>

                <?php if(count($actions)): ?>
                    <th width="5%">Ações</th>
                <?php endif; ?>

            </tr>
        </thead>
        <tbody>
            <?php if(count($data)): ?>
                <?php foreach ($data as $row): ?>
                    <tr>
                        <?php foreach ($columns as $col => $config): ?>

                            <?php $attrs = ''; ?>

                            <?php if(isset($config['options']) && isset($config['options']['attributes'])): ?>
                                <?php foreach($config['options']['attributes'] as $attr => $attrVal): ?>

                                    <?php $attrs.= "{$attr}=\"{$attrVal}\" "; ?>

                                <?php endforeach; ?>
                            <?php endif; ?>
                            <?php $methodGet = "get" . ucfirst($col); ?>
                            <?php $val = $row->$methodGet(); ?>

                            <td <?php echo $attrs ?>><?php echo $config['methodGet'] ? call_user_func($config['methodGet'], $val, $row) : $val ?></td>

                        <?php endforeach; ?>

                        <?php if(count($actions)): ?>
                            <td class="text-center">
                                <?php foreach($actions as $type => $action): ?>
                                    <?php $urlAction = array() ?>
                                    <?php if($type == \Rubix\View\Components\Datagrid::ACTION_EDIT) { $urlAction = $url['edit']; } ?>
                                    <?php if($type == \Rubix\View\Components\Datagrid::ACTION_REMOVE) { $urlAction = $url['remove']; } ?>
                                    <?php $urlAction['id'] = $row->$getIdMethodName(); ?>

                                    <a class="rubix-color" href="<?php echo $this->url(null, $urlAction) ?>"><span class="glyphicon glyphicon-<?php echo $action['icon'] ?>"></span></a>

                                <?php endforeach; ?>
                            </td>
                        <?php endif; ?>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="<?php echo count($columns) + count($actions) ?>"><?php echo $this->translator('Nenhum resultado encontrado.') ?></td>
                </tr>
            <?php endif; ?>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="<?php echo count($columns) + count($actions) ?>" class="text-center">
                    <?php echo $this->paginationControl($data, 'sliding', array('components/paginator.phtml', 'Usuarios'), array('route' => $url['paginator'])) ?>
                </td>
            </tr>
        </tfoot>
    </table>

</div>