<div class="panel panel-default panel-datagrid">
    <div class="panel-heading">
        <?php echo $title ?>
        <?php if(count($header)): ?>
            <p class="pull-right">
                <?php foreach($header as $link): ?>
                    <?php
                    $type = '';
                    switch($link['type']) :
                        case \Rubix\View\Components\Datagrid::HEADER_BUTTON:
                            $type = 'warning';
                            break;
                        case \Rubix\View\Components\Datagrid::HEADER_LINK:
                            $type = 'link';
                            break;
                    endswitch;
                    ?>
                    <a class="btn btn-xs btn-<?php echo $type ?>" href="<?php echo $this->url(null, $link['link']); ?>">
                        <?php if($link['icon']): ?>
                            <span class="glyphicon glyphicon-<?php echo $link['icon'] ?>"></span>
                        <?php endif; ?>
                        <?php echo $link['label'] ?>
                    </a>
                <?php endforeach; ?>
            </p>
        <?php endif; ?>
    </div>

    <?php if($filter && $form): ?>
        <?php $form->prepare(); ?>
        <div class="panel-body">
                <?php echo $this->form()->openTag($form); ?>
                <input type="hidden" name="_sortfield" value="<?php echo $request->getQuery()->get('_sortfield') ?>" />
                <input type="hidden" name="_sortorder" value="<?php echo $request->getQuery()->get('_sortorder') ?>" />
                <?php foreach($filter as $field): ?>
                    <div class="form-group">
                        <?php echo $field['labelField'] ? $this->formLabel($form->get($field['labelField']), $field['label']) : ''; ?>
                        <div class="<?php echo $field['class'] ?>">
                            <?php echo $this->$field['render']($form->get($field['name'])); ?>
                        </div>
                    </div>
                <?php endforeach; ?>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    <?php endif; ?>

    <table class="table table-bordered table-condensed table-hover table-responsive table-striped datagrid">
        <?php if(count($data)): ?>
        <thead>
            <tr>
                <?php foreach ($columns as $name => $col): ?>
                    <?php $attrs = ''; ?>
                    <?php if(isset($col['options']) && isset($col['options']['attributes'])): ?>
                        <?php foreach($col['options']['attributes'] as $attr => $val): ?>
                            <?php $attrs.= "{$attr}=\"{$val}\" "; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    <th <?php echo $attrs ?>>
                        <?php echo $col['label'] ?>
                        <?php if($col['aliasOrderBy']): ?>
                            <?php $_tmp = $queryParams ?>
                            <?php $_tmp['_sortfield'] = $name ?>
                            <?php $_tmp['_sortorder'] = $sortOrder ?>
                            <a href="<?php echo $this->url(null, $url['paginator']); ?>?<?php echo http_build_query($_tmp); ?>">
                                <span class="<?php echo $name == $sortField ? 'rubix-color' : '' ?> datagrid-sorter glyphicon glyphicon-sort"></span>
                            </a>
                        <?php endif; ?>
                    </th>
                <?php endforeach; ?>
                <?php if(count($actions)): ?>
                    <th width="5%">Ações</th>
                <?php endif; ?>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($data as $row): ?>
                <tr>
                    <?php foreach ($columns as $col => $config): ?>
                        <?php $attrs = ''; ?>
                        <?php if(isset($config['options']) && isset($config['options']['attributes'])): ?>
                            <?php foreach($config['options']['attributes'] as $attr => $attrVal): ?>

                                <?php $attrs.= "{$attr}=\"{$attrVal}\" "; ?>

                            <?php endforeach; ?>
                        <?php endif; ?>
                        <?php $methodGet = "get" . ucfirst($col); ?>
                        <?php $val = $row->$methodGet(); ?>
                        <td <?php echo $attrs ?>><?php echo $config['methodGet'] ? call_user_func($config['methodGet'], $val, $row) : $val ?></td>
                    <?php endforeach; ?>
                    <?php if(count($actions)): ?>
                        <td class="text-center">
                            <?php foreach($actions as $type => $action): ?>
                                <?php $urlAction = array() ?>
                                <?php if($type == \Rubix\View\Components\Datagrid::ACTION_EDIT) { $urlAction = $url['edit']; } ?>
                                <?php if($type == \Rubix\View\Components\Datagrid::ACTION_REMOVE) { $urlAction = $url['remove']; } ?>
                                <?php $urlAction['id'] = $row->$getIdMethodName(); ?>

                                <?php if($action['jsCallback']): ?>
                                    <a class="rubix-color <?php echo $action['cssClass'] ?>" onclick="<?php echo "{$action['jsCallback']}(this)" ?>" data-id="<?php echo $row->$getIdMethodName() ?>" data-href="<?php echo $this->url(null, $urlAction) ?>"><span class="glyphicon glyphicon-<?php echo $action['icon'] ?>"></span></a>
                                <?php elseif($type == \Rubix\View\Components\Datagrid::ACTION_REMOVE): ?>
                                    <a data-html="true" data-placement="left" data-toggle="popover" data-content="<div class='text-left'>Deseja mesmo excluir este item? <button class='btn btn-primary' onclick='DataGrid.confirmarExclusaoCallback(this)'>Sim</button> <button data-dismiss='popover' onclick='DataGrid.cancelarExclusaoCallback(this)' class='btn btn-danger btn-cancelar-delete'>Cancelar</button></div>" class="rubix-color <?php echo $action['cssClass'] ?>" data-id="<?php echo $row->$getIdMethodName() ?>" data-href="<?php echo $this->url(null, $urlAction) ?>"><span class="glyphicon glyphicon-<?php echo $action['icon'] ?>"></span></a>
                                <?php else: ?>
                                    <a class="rubix-color <?php echo $action['cssClass'] ?>" href="<?php echo $this->url(null, $urlAction) ?>"><span class="glyphicon glyphicon-<?php echo $action['icon'] ?>"></span></a>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </td>
                    <?php endif; ?>
                </tr>
            <?php endforeach; ?>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="<?php echo count($columns) + count($actions) ?>" class="text-center">
                    <?php echo $this->paginationControl($data, 'sliding', array('components/paginator.phtml', 'Usuarios'), array('route' => $url['paginator'])) ?>
                </td>
            </tr>
        </tfoot>
        <?php else: ?>
            <tbody>
                <tr>
                    <td><?php echo $this->translate('Nenhum resultado encontrado.') ?></td>
                </tr>
            </tbody>
        <?php endif; ?>
    </table>
</div>