<?php
$form = $this->form;
$form->prepare();
?>

<div class="tabbable">
    <?php echo $this->menu_principal; ?>
    <div class="tab-content">
        <p>
        <h1><?php echo $this->escapeHtml('Acessos'); ?></h1>
        <p>
        <form class="form-horizontal">
            <?php echo $this->formRow($form->get('int_perfil')); ?>
        </form>
        </p>
        <p class="pull-right">
            <small class="btn btn-mini"><a href="#" class="selecionarTodas">Todos</a></small>
            <small class="btn btn-mini"><a href="#" class="selecionarNenhuma">Nenhum</a></small>
        </p>
        <br class="clearfix" />
        <br />

        <?php echo $this->form()->openTag($form); ?>

        <input type="hidden" name="int_perfil" value="<?php echo $this->codPerfil; ?>" />

        <table class="table table-bordered table-hover table-condensed" id="tb-acessos">
            <?php foreach ($this->actions as $_controller => $_actions) : ?>
                <tr class="info">
                    <td colspan="2">
                        <span class="pull-left">
                            <div class="<?php echo str_replace('\\', '-', $_controller) ?>"><strong><?php echo $_controller ?></strong></div>
                        </span>
                        <p class="pull-right">
                            <small class="btn btn-mini"><a href="#" class="selecionarTodasActions">Todos</a></small>
                            <small class="btn btn-mini"><a href="#" class="selecionarNenhumaAction">Nenhum</a></small>
                        </p>
                    </td>
                </tr>
                <?php foreach ($_actions as $_action) : ?>
                    <?php $checked = key_exists($_controller, $this->acessos) && isset($this->acessos[$_controller][$_action]) ? 'checked="on"' : ''; ?>
                    <tr>
                        <td width="50%">
                            <input type="checkbox" <?php echo $checked; ?> class="<?php echo str_replace('\\', '-', $_controller) ?>" name="<?php echo "{$_controller}[{$_action}]" ?>" /> <?php echo $_action ?>
                        </td>
                        <td class="muted">
                            <?php
                            if (isset($comments[$_controller]) && isset($comments[$_controller][$_action])) {
                                echo $comments[$_controller][$_action];
                            }
                            ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php endforeach; ?>
        </table>
        <div class="control-group">
            <div class="controls">
                <?php echo $this->formSubmit($form->get('submit')); ?>
            </div>
        </div>
        <?php echo $this->form()->closeTag(); ?>
        </p>
    </div>
</div>