<div class="thumbnail well">
    <h4>Contato</h4>
    <hr />
    <form method="post" id="fmContato" class="form-horizontal">
        <div class="control-group">
            <label for="nm-nome" class="control-label">Nome completo</label>
            <div class="controls">
                <input type="text" data-trigger="focus" title="Informe o Nome Completo" placeholder="Nome completo" id="nm-nome" name="nmNome">
            </div>
        </div>
        <div class="control-group">
            <label for="nm-email" class="control-label">Email</label>
            <div class="controls">
                <input type="text" data-trigger="focus" title="Informe o Email" placeholder="Email" id="nm-email" name="nmEmail">
            </div>
        </div>
        <div class="control-group">
            <label for="nr-telefone" class="control-label">Telefone</label>
            <div class="controls">
                <input type="text" data-trigger="focus" title="Informe o Telefone" data-mask="(99) 9999-9999" placeholder="Telefone" class="input-medium" id="nr-telefone" name="nrTelefone">
            </div>
        </div>
        <div class="control-group">
            <label for="tx-comentarios" class="control-label">Comentários e informações adicionais</label>
            <div class="controls">
                <textarea data-trigger="focus" placeholder="Comentários" title="Informe os Comentários" class="input-xlarge" name="txComentarios" id="tx-comentarios"></textarea>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <button class="btn  btn-primary" title="Enviar formulário" id="btEnviarContato" type="submit">Enviar</button>
            </div>
        </div>
    </form>
    <hr />
    <p>
        <small>
            <ul class="unstyled">
                <li>
                    <span class="label label-info">E-mail</span>&nbsp; contato@fontesolutions.com.br
                </li>
                <li>
                    <span class="label label-info">Celular</span>&nbsp; 55 (61) 9621-2011<br>
                </li>
                <li>
                    <span class="label label-info">Comercial</span>&nbsp; 55 (61) 3046-5726<br>
                </li>
            </ul>
        </small>
    </p>
</div>