<div class="row-fluid">
    <div class="span8 well">
        Block Left
    </div>
    <div class="span4 well">
        Block Right
    </div>
</div>

<div class="row-fluid main-blocks">
    <ul class="thumbnails">
        <li class="span4 well">
            A
        </li>
        <li class="span4 well">
            B
        </li>
        <li class="span4 well">
            C
        </li>
    </ul>
</div>
