<div class="row-fluid">
    <div class="span8 well">
        L
    </div>
    <div class="span4 well">
        R
    </div>
</div>

<div class="row-fluid main-blocks">
    <ul class="thumbnails">
        <li class="span4 well">
            A
        </li>
        <li class="span4 well">
            B
        </li>
        <li class="span4 well">
            C
        </li>
    </ul>
</div>

<div class="row-fluid main-blocks">
    <ul class="thumbnails">
        <li class="span4 well">
            D
        </li>
        <li class="span4 well">
            E
        </li>
        <li class="span4 well">
            F
        </li>
    </ul>
</div>
