<div class="hero-unit">
    <h1><span class="fs-red"><?php echo $this->translate('Quem somos') ?></span></h1>
    <p><?php echo $this->translate('A FonteSolutions é uma empresa de tecnologia em atividade desde 2011, focada em inovação, buscando trazer confiança, facilidade e maior produtividade no dia-a-dia utilizando soluções informatizadas...') ?></p>
    <p><a class="btn btn-danger btn-large" href="./"><?php echo $this->translate('Leia mais') ?> &raquo;</a></p>
</div>

<div class="row-fluid" id="blo-destaques">
    <ul class="thumbnails">
        <li class="span4">
            <div class="thumbnail well">
                <div class="caption">
                    <h3 class="fs-red"><?php echo $this->translate('Qualidade, Rapidez e Segurança') ?></h3>
                    <p><?php echo $this->translate('Nossos profissionais são altamente qualificados no mercado de trabalho, com vasta experiência em desenvolvimento de sistemas de gestão, governamentais e de automação comercial.') ?></p>
                    <p>
                        <a class="btn btn-danger pull-right" href="<?php echo $this->url('quem-somos') ?>"><?php echo $this->translate('Leia mais') ?> &raquo;</a>
                    </p>
                    <span class="clearfix"></span>
                </div>
            </div>
        </li>
        <li class="span4">
            <div class="thumbnail well">
                <div class="caption">
                    <h3 class="fs-red"><?php echo $this->translate('Serviços') ?></h3>
                    <p><?php echo $this->translate('A FonteSolutions oferece seus serviços de desenvolvimento tanto a empresas com sistemas sob medida, como a comunidade de desenvolvimento, com sistemas de licença Opensource...') ?></p>
                    <p>
                        <a class="btn btn-danger pull-right" href="<?php echo $this->url('servicos') ?>"><?php echo $this->translate('Leia mais') ?> &raquo;</a>
                    </p>
                    <span class="clearfix"></span>
                </div>
            </div>
        </li>
        <li class="span4">
            <div class="thumbnail well">
                <div class="caption">
                    <h3 class="fs-red"><?php echo $this->translate('Suporte') ?></h3>
                    <p><?php echo $this->translate('A FonteSolutions disponibiliza suporte integrado em suas soluções, com acesso direto ao serviço de Suporte ao Usuário. Esse suporte também poderá ser acessado externamente pelo usuário. Cada cliente...') ?></p>
                    <p>
                        <a class="btn btn-danger pull-right" href="<?php echo $this->url('suporte') ?>"><?php echo $this->translate('Leia mais') ?> &raquo;</a>
                    </p>
                    <span class="clearfix"></span>
                </div>
            </div>
        </li>
    </ul>
</div>
